.PHONY: clean

CFLAGS=-std=c99 -Wall -Werror
TARGET=ex1-13 ex1-16 ex1-17 ex1-18 ex1-19 ex1-20 \
	ex2-3 ex2-4 ex2-5 ex2-6 ex2-7 ex2-8 ex2-9 \
	ex3-1 shell-sort ex3-3 ex3-4

all: $(TARGET)

clean:
	-rm -rf $(TARGET)
